version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"

- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: "UTC"
  open-pull-requests-limit: 100
